script = {
	a: new Ln(['"Wow, I\'ve been down here for month..."'], ['b'], 'fish'),
	b: new Ln(['"Or maybe I\'ve been down here for years?"'], ['c'], 'fish'),
	c: new Ln(['"Gosh, I can\'t tell anymore..."'], ['d'], 'fish'),
	d: new Ln(['???: "Hello there!"'], ['e'], 'fish'),
	e: new Ln(['You look around fervently, trying to find the source of the speaker.'], ['f'], 'fish'),
	f: new Ln(['But you don\'t find anybody remotely human-shaped...'], ['g'], 'fish'),
	g: new Ln(['???: "Hellooooo?"'], ['h'], 'fish'),
	h: new Ln(['A fish - an angler fish, with its bright bulb flashing in your vision - bonks into your helmet\'s visor.'], ['i'], 'fish'),
	i: new Ln(['Like it\'s trying to get your attention.'], ['j'], 'fish'),
	j: new Ln(['Wait...'], ['k'], 'fish'),
	k: new Ln(['Is the fish trying to get your attention?!'], ['l'], 'fish'),
	l: new Ln(['Fish?: "Hello there, large fren!"'], ['m'], 'fish'),
	m: new Ln(['"Umm... hello."'], ['n'], 'fish'),
	n: new Ln(['Fish?: "Oh!"'], ['o'], 'fish'),
	o: new Ln(['The fish zooms around in a circle excitedly, causing bubbles to appear around it.'], ['p'], 'fish'),
	p: new Ln(['Fish?: "You can understand me! How refreshing."'], ['q'], 'fish'),
	q: new Ch(['Say hello again.', 'Scream bloody murder.'], ['r'], 'fish'),
	r: new Ln(['"Hello...?"'], ['s'], 'fish'),
	s: new Ln(['Fish: "Hello!!"'], ['t'], 'fish'),
	t: new Ln(['The fish excitedly swims in circles again, before coming up to you.'], ['u'], 'fish'),
	u: new Ln(['Flashing its incredibly creepy, large, and jagged teeth.'], ['v'], 'fish'),
	v: new Ln(['Fish: "What kind of human are you?"'], ['w'], 'fish'),
	w: new Ln(['"I\'m... I\'m a human?"'], ['x'], 'fish'),
	x: new Ln(['Fish: "Hoo...man? I\'m afraid I don\'t know what that is."'], ['y'], 'fish'),
	y: new Ln(['"I\'m not a fish-"'], ['z'], 'fish'),
	z: new Ln(['Fish: "That\'s okay, hooman! We can still be friends."'], ['a1'], 'fish'),
	a1: new Ln(['"Uh... okay..."'], ['a2'], 'fish'),
	a2: new Ln(['Guess you\'re friends now.'], ['a2'], 'fish'),

}